#!/usr/bin/env bash

# Pull latest changes for all git repositories in subdirectories

# Navigate up one directory to access sibling repositories
cd ..

# Find all directories containing .git (git repositories)
for dir in */; do
    if [ -d "$dir/.git" ]; then
        echo "Pulling $dir..."
        git -C "$dir" pull
        echo
    fi
done

echo "Done!"
