#!/usr/bin/env bash
# install-mcpc-skill.sh - (Re)generate the mcpc agent skill from the installed mcpc CLI
#
# mcpc is a universal CLI client for the Model Context Protocol (MCP):
#   https://github.com/apify/mcpc
#
# This script runs `mcpc help --skill` and writes the output to
# wi-mcpc/mcpc-tool.md so that wi-base/refresh-skills.sh symlinks it into
# .pi/skills/ and .opencode/skills/.
#
# The file is recreated on every run, so re-run this after upgrading @apify/mcpc
# to refresh the snapshot (mcpc's built-in skill always matches the installed
# version; this script captures that snapshot into the repo).
#
# If the mcpc CLI (or npm) is not already on PATH, this script installs the
# missing prerequisite automatically so a fresh checkout always produces the
# skill without manual setup:
#   npm install -g @apify/mcpc
#
# Usage: ./repo-utils/install-mcpc-skill.sh
# Exit codes: 0 = success, non-zero = error

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILL_DIR="$REPO_ROOT/wi-mcpc"
SKILL_FILE="$SKILL_DIR/mcpc-tool.md"
README_FILE="$SKILL_DIR/README.md"

# --- prerequisites -----------------------------------------------------------
# Auto-install mcpc so the script is self-bootstrapping on a fresh checkout.
# mcpc ships as the npm package @apify/mcpc; if it is absent from PATH we
# install it via npm. Node.js/npm itself is a hard prerequisite — if npm is
# missing we fail and let the operator install Node.js by hand.

if ! command -v npm >/dev/null 2>&1; then
    echo "Error: npm not found on PATH. Install Node.js/npm first." >&2
    exit 1
fi

if ! command -v mcpc >/dev/null 2>&1; then
    echo "mcpc CLI not found on PATH; installing @apify/mcpc via npm..." >&2
    npm install -g @apify/mcpc
fi

mcpc_version=$(mcpc --version 2>/dev/null || echo "unknown")

# --- generate the skill snapshot ---------------------------------------------
# Write to a temp file first, validate it, then atomically move into place so a
# failed or interrupted run never corrupts an existing good skill file.
tmp_file=$(mktemp)
trap 'rm -f "$tmp_file"' EXIT

if ! mcpc help --skill > "$tmp_file"; then
    echo "Error: 'mcpc help --skill' failed." >&2
    exit 1
fi

# Validate the snapshot looks like a SKILL.md: frontmatter with a name field.
# Mirrors the validation in wi-base/refresh-skills.sh so the two scripts agree.
skill_name=$(sed -n '/^---$/,/^---$/{/^---$/d; /^name: /p}' "$tmp_file" | sed 's/^name: //' | head -1)

if [[ -z "$skill_name" ]]; then
    echo "Error: 'mcpc help --skill' output is missing frontmatter 'name'." >&2
    exit 1
fi

if [[ ! "$skill_name" =~ ^[a-z0-9]+(-[a-z0-9]+)*$ ]]; then
    echo "Error: mcpc skill has invalid name '$skill_name' (must be lowercase, digits, hyphens)." >&2
    exit 1
fi

# Workspace convention requires the type suffix on the published skill name
# (refresh-skills.sh audits this). Rewrite 'mcpc' -> 'mcpc-tool' before write.
if [[ "$skill_name" == "mcpc" ]]; then
    sed -i '0,/^name: mcpc$/{s|^name: mcpc$|name: mcpc-tool|}' "$tmp_file"
    skill_name="mcpc-tool"
    echo "Note: rewrote name 'mcpc' -> 'mcpc-tool' (workspace convention requires type suffix)"
fi

if [[ "$skill_name" != "mcpc-tool" ]]; then
    echo "Warning: expected skill name 'mcpc-tool' but got '$skill_name'." >&2
fi

mkdir -p "$SKILL_DIR"

# Append a generation marker as an HTML comment so anyone reading the file can
# see which mcpc version the snapshot came from and when it was captured. The
# comment is after the closing frontmatter `---` and is invisible to markdown
# renderers and skill loaders.
{
    cat "$tmp_file"
    echo ""
    echo "<!-- Generated from 'mcpc help --skill' (mcpc v${mcpc_version}) on $(date -u +%Y-%m-%d) by repo-utils/install-mcpc-skill.sh -->"
} > "$SKILL_FILE"

echo "Refreshed mcpc skill: $SKILL_FILE"
echo "  mcpc version: v${mcpc_version}"
echo "  skill name:   ${skill_name}"
echo ""
# Write a README.md explaining that this directory and the skill snapshot within
# it are generated by this script, so users don't hand-edit them. Recreated on
# every run so it stays accurate and the script stays idempotent.
cat > "$README_FILE" <<'EOF'
# mcpc skill

This directory and the `mcpc-tool.md` skill snapshot inside it are generated by
[`repo-utils/install-mcpc-skill.sh`](../repo-utils/install-mcpc-skill.sh).

Do not edit these files by hand — they are recreated from `mcpc help --skill`
on each run of that script. Re-run it after upgrading `@apify/mcpc` to refresh
the snapshot:

```bash
./repo-utils/install-mcpc-skill.sh
```

Then run `./wi-base/refresh-skills.sh` to (re)create the `.pi/skills/` and
`.opencode/skills/` symlinks.
EOF

echo "Next: run ./wi-base/refresh-skills.sh to (re)create the .pi/skills/ and .opencode/skills/ symlinks."
